### ISSUE TITLE
`decoding input: no icons found`

### ISSUE THREAD

**Issue by nbolton** [JackMordaunt/icns#31]
```
% icnsify -i App.icns -o App.png       
2024/09/26 20:25:56 decoding input: no icons found
```

[App.icns.zip](https://github.com/user-attachments/files/17155080/App.icns.zip)

Any help would be appreciated!

# Workaround

Use the native Apple command:
```
sips -s format png App.icns --out App.png
```

**Comment by JackMordaunt** [comment]
Hi @nbolton! Your icns file contains JPEG 2000 data which is being skipped. Using PNG source images will work. More specifically, this is only a problem because your icns file contains exactly one icon that is the JPEG 2000. Thus it gets skipped and there are not other viable icons to use hence "no icons found".

Apologies for the confusion, I'll add some logging output so that this kind of fail case is explained to the user in lieu of supporting JPEG 2000 images. 

JPEG 2000 is not natively supported by Go and there doesn't appear to be any solid decoders for it (in Go).

**Comment by JackMordaunt** [comment]
I've pushed an update that provides more helpful output related to this issue.
