### ISSUE TITLE
Creates invalid (?) icns files

### ISSUE THREAD

**Issue by Barteks2x** [JackMordaunt/icns#4]
I was trying to use this tool on linux to convert a png to icns file. It seemed to work and produced some file, but I was unable to actually open that file with anything. 

Even image magick gives up on this with the folliwing output:

```
$ magick convert source-file.icns converted-file.png 
convert: no decode delegate for this image format `ICNS' @ error/constitute.c/ReadImage/562.
convert: no images defined `converted-file.png' @ error/convert.c/ConvertImageCommand/3282.
```

`ImageMagick` creates a valid icns file from the same source png.

**Comment by JackMordaunt** [comment]
This utility emits a header at the beginning of the icns file (specified [here](https://en.wikipedia.org/wiki/Apple_Icon_Image_format)):

Offset | Size | Purpose
-- | -- | --
0 | 4 | Magic literal, must be "icns" (0x69, 0x63, 0x6e, 0x73)
4 | 4 | Length of file, in bytes, msb first

If you look at a hex dump you'll see the imagemagick version (on the right) does not actually have this header.

<img width="1429" alt="hex-diff" src="https://user-images.githubusercontent.com/6916093/82115835-d6ee0380-9797-11ea-8e43-c1e7f2986fbc.png">

It seems to be that the imagemagick version does not give it's icns file a header, nor does it expect one when decoding, and bails out when it sees it. 

I don't think this is "invalid" on the part of `jackmordaunt/icns` utility, since the icons work on MacOS (aka finder previews them just fine) and the spec on wikipedia says to use a header. 

It may be that the header is actually optional, or that imagemagick is incorrect and should in fact use a header. 

Either way, would you like to produce "imagemagick compatible" icns files? It seems we could simply omit the header with a flag. 

I would also like to test on a mac, to see if an icns image without a header still displays correctly.

**Comment by Barteks2x** [comment]
I don't actually have a mac to test any of this on, I would need to ask some mac user to see if it works for them.

That said none of my linux tools were able to open the icns file with header. I got reports that .app with that icon was "invalid" but macos didn't give any details and I changed more than just icon with the version that fixed it, so I can't be entirely sure.

**Comment by JackMordaunt** [comment]
I did some digging on my Mac. 

When you create an `.icns` file without the header, since the png data is at the start, it simply gets treated as a png image. The trailing data (the other png images inside the icns) simply get ignored. 

With the header, Preview displays it correctly as a ICNS:

<img width="1380" alt="working-header" src="https://user-images.githubusercontent.com/6916093/82135901-82e82b00-983a-11ea-8bc3-825f3adfb808.png">

Without the header, Preview displays it as only the first png that it can see (even though they are all still in the file):

<img width="1380" alt="working-no-header" src="https://user-images.githubusercontent.com/6916093/82135904-8976a280-983a-11ea-98d9-53ed3a6eb31e.png">

The only difference between these two images is that I deleted the first 8 bytes of the file, which is the header.

So, perhaps the `imagemagick` "solution" is simply to render a single png with an `.icns` extension, since it knows MacOS utilities will still "use" such a file?

Given that MacOS prefers the header to exist, does this mean that the imagemagick handling of `.icns` is bugged since it won't correctly parse the ICNS 8 byte header?

**Comment by Barteks2x** [comment]
That would appear to be the case. Then maybe linux seeing the contents of .icns files was just an artifact of them actually being PNGs.

**Comment by JackMordaunt** [comment]
I’m currently working on some ICNS integration with Windows Explorer via a shell extension. I don’t think any standard Linux apps will recognise the format, and would likely require a similar approach if you wanted “first class” support.
